.TH py3rsa\-sign 1
.SH NAME
\fBpy3rsa\-sign\fP \- sign a file
.SH SYNOPSIS
\fBpy3rsa\-sign\fP [\fI\,OPTION\/\fR]... \fI\,PRIVATE_KEY HASH_METHOD\/\fR
.SH DESCRIPTION
Sign a file, output the signature. Choose the hash method from MD5, SHA\-1, SHA\-224, SHA\-256, SHA\-384, SHA\-512
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show help message and exit
.TP
\fB\-i \fIINPUT\fR, \fB\-\-input=\fIINPUT\fR
name of the file to sign. read from stdin if not specified.
.TP
\fB\-i \fIOUTPUT\fR, \fB\-\-output=\fIOUTPUT\fR
name of the file to write the signature to. write to stdout if this option is not present.
.TP
\fB\-\-keyform=\fIKEYFORM\fR
key format of the private key \- default PEM
.SH AUTHOR
\fB\,py3rsa\-sign\fR was written by Sybren A. Stuvel <sybren AT stuvel.eu>.
